apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends-latest
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - name: techtrends
        image: tts2k/techtrends:latest
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbePath }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10

