namespace:
  name: sandbox

replicas: 1

image:
  repository: tts2k/techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 64
  limits:
    cpu: 500m
    memory: 128Mi

service:
  port: 8111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

containerPort: &containerPort 3111

livenessProbe:
  path: /healthz
  port: *containerPort

readinessProbe:
  path: /healthz
  port: *containerPort
